### ISSUE TITLE
xboxdrv doesn't define the ID_BUS udev property for virtual devices

### ISSUE THREAD

**Issue by c02y** [foresto/joystickwake#12]
Recently, Arch Linux upgrades python version to v3.11.3, so joystickwake won't work anymore:
```
>> /tmp/joystickwake
Traceback (most recent call last):
  File "/tmp/joystickwake", line 653, in <module>
    main()
  File "/tmp/joystickwake", line 645, in main
    loop.run_until_complete(watcher.start())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/joystickwake", line 355, in start
    self._watch_known_joysticks()
  File "/tmp/joystickwake", line 365, in _watch_known_joysticks
    self._watch_device(device)
  File "/tmp/joystickwake", line 427, in _watch_device
    device.sys_name, self._get_device_description(device))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/joystickwake", line 392, in _get_device_description
    return ' '.join((vendor, model, bus)).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, NoneType found
```

**Comment by c02y** [comment]
**UPDATE**:

It seems this is not the Python version problem, or, maybe it is, I'm not sure, anyway. I found that if my game controller is virtual device from xboxdrv using command like
```
xboxdrv --type xbox360 --device-by-id 413d:2104 --silent --quiet --detach-kernel-driver --mimic-xpad --force-feedback
```
Then `vendor`, `model`, `bus` are all none from [def _get_device_description(device):](https://github.com/foresto/joystickwake/blob/72791f18b6a38ee3777d7b728fc8947552d161ec/joystickwake#LL384C37-L384C37), the device is something like:
```
# if new device added after joystickwake is executed:
/sys/devices/virtual/input/input84/js0

# or if old device added before joystickwake is executed:
/sys/devices/virtual/input/input90/event27
```
joystickwake failed to handle such device.

If it is not mimic, `vendor`, `model`, `bus` are all valid values, joystickwake works fine, the device is:
```
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.004A/input/input87/js0
# or
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0043/input/input81/event26
```

But if I change https://github.com/foresto/joystickwake/blob/72791f18b6a38ee3777d7b728fc8947552d161ec/joystickwake#LL384C37-L384C37
from
```
if bus:
    bus = '(' + bus + ')'
return ' '.join((vendor, model, bus)).strip()
```
to
```
if bus:
    bus = '(' + bus + ')'
    return ' '.join((vendor, model, bus)).strip()
```
The joystickwake script works without problem, at least for me, `waking the screen` part works.

**Comment by foresto** [comment]
Indeed, the problem is triggered by xboxdrv not defining some udev properties that joystickwake expects. The python version has nothing to do with it.

Can you post the output of these commands while using the xboxdrv virtual device? (You'll need to replace the input/js/event numbers with the ones on your system, of course.)

    udevadm info -q all -p /devices/virtual/input/input84/js0
    udevadm info -q all -p /devices/virtual/input/input84
    udevadm info -q all -p /devices/virtual/input/input90/event27
    udevadm info -q all -p /devices/virtual/input/input90

**Comment by c02y** [comment]
Sorry, only one virtual/input in `cat /proc/bus/input/devices`

```
>> udevadm info -q all -p /devices/virtual/input/input104/js0
P: /devices/virtual/input/input104/js0
M: js0
R: 0
U: input
D: c 13:0
N: input/js0
L: 0
E: DEVPATH=/devices/virtual/input/input104/js0
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/js0
E: MAJOR=13
E: MINOR=0
E: USEC_INITIALIZED=55542488374
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_SERIAL=noserial
E: TAGS=:seat:uaccess:
E: CURRENT_TAGS=:seat:uaccess:

>> udevadm info -q all -p /devices/virtual/input/input104
P: /devices/virtual/input/input104
M: input104
R: 104
U: input
E: DEVPATH=/devices/virtual/input/input104
E: SUBSYSTEM=input
E: PRODUCT=3/45e/28e/110
E: NAME="Microsoft X-Box 360 pad"
E: PROP=0
E: EV=20000b
E: KEY=7cdb000000000000 0 0 0 0
E: ABS=3003f
E: FF=13f870000 0
E: MODALIAS=input:b0003v045Ep028Ee0110-e0,1,3,15,k130,131,133,134,136,137,13A,13B,13C,13D,13E,ra0,1,2,3,4,5,10,11,mlsf50,51,52,57,58,59,5A,5B,5C,5D,60,w
E: USEC_INITIALIZED=55542486103
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_SERIAL=noserial
E: TAGS=:seat:
E: CURRENT_TAGS=:seat:

>> udevadm info -q all -p /devices/virtual/input/input104/event27
P: /devices/virtual/input/input104/event27
M: event27
R: 27
U: input
D: c 13:91
N: input/event27
L: 0
E: DEVPATH=/devices/virtual/input/input104/event27
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/event27
E: MAJOR=13
E: MINOR=91
E: USEC_INITIALIZED=55542497609
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_SERIAL=noserial
E: TAGS=:seat:uaccess:
E: CURRENT_TAGS=:seat:uaccess:
```
-----------------------------------------
**UPDATE**:
FYI: if not virtual:
```
>> udevadm info -q all -p /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105
P: /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105
M: input105
R: 105
U: input
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105
E: SUBSYSTEM=input
E: PRODUCT=3/57e/2009/8111
E: NAME="Nintendo Switch Pro Controller"
E: PHYS="usb-0000:00:14.0-5.3/input0"
E: UNIQ="00:04:04:07:20:84"
E: PROP=0
E: EV=20000b
E: KEY=7ffb000000000000 0 0 0 0
E: ABS=3001b
E: FF=107030000 0
E: MODALIAS=input:b0003v057Ep2009e8111-e0,1,3,15,k130,131,133,134,135,136,137,138,139,13A,13B,13C,13D,13E,ra0,1,3,4,10,11,mlsf50,51,58,59,5A,60,w
E: USEC_INITIALIZED=56177682391
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_BUS=usb
E: ID_MODEL=Pro_Controller
E: ID_MODEL_ENC=Pro\x20Controller
E: ID_MODEL_ID=2009
E: ID_SERIAL=Zikway_Pro_Controller_314838353800c9c4
E: ID_SERIAL_SHORT=314838353800c9c4
E: ID_VENDOR=Zikway
E: ID_VENDOR_ENC=Zikway
E: ID_VENDOR_ID=057e
E: ID_REVISION=0200
E: ID_TYPE=hid
E: ID_USB_MODEL=Pro_Controller
E: ID_USB_MODEL_ENC=Pro\x20Controller
E: ID_USB_MODEL_ID=2009
E: ID_USB_SERIAL=Zikway_Pro_Controller_314838353800c9c4
E: ID_USB_SERIAL_SHORT=314838353800c9c4
E: ID_USB_VENDOR=Zikway
E: ID_USB_VENDOR_ENC=Zikway
E: ID_USB_VENDOR_ID=057e
E: ID_USB_REVISION=0200
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:5.3:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_5_3_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_5_3_1_0
E: TAGS=:seat:
E: CURRENT_TAGS=:seat:

>> udevadm info -q all -p /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105/js1
P: /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105/js1
M: js1
R: 1
U: input
D: c 13:1
N: input/js1
L: 0
S: input/by-id/usb-Zikway_Pro_Controller_314838353800c9c4-joystick
S: input/by-path/pci-0000:00:14.0-usb-0:5.3:1.0-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5.3/1-5.3:1.0/0003:057E:2009.0058/input/input105/js1
E: SUBSYSTEM=input
E: DEVNAME=/dev/input/js1
E: MAJOR=13
E: MINOR=1
E: USEC_INITIALIZED=56177683610
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_BUS=usb
E: ID_MODEL=Pro_Controller
E: ID_MODEL_ENC=Pro\x20Controller
E: ID_MODEL_ID=2009
E: ID_SERIAL=Zikway_Pro_Controller_314838353800c9c4
E: ID_SERIAL_SHORT=314838353800c9c4
E: ID_VENDOR=Zikway
E: ID_VENDOR_ENC=Zikway
E: ID_VENDOR_ID=057e
E: ID_REVISION=0200
E: ID_TYPE=hid
E: ID_USB_MODEL=Pro_Controller
E: ID_USB_MODEL_ENC=Pro\x20Controller
E: ID_USB_MODEL_ID=2009
E: ID_USB_SERIAL=Zikway_Pro_Controller_314838353800c9c4
E: ID_USB_SERIAL_SHORT=314838353800c9c4
E: ID_USB_VENDOR=Zikway
E: ID_USB_VENDOR_ENC=Zikway
E: ID_USB_VENDOR_ID=057e
E: ID_USB_REVISION=0200
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:5.3:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_5_3_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_5_3_1_0
E: DEVLINKS=/dev/input/by-id/usb-Zikway_Pro_Controller_314838353800c9c4-joystick /dev/input/by-path/pci-0000:00:14.0-usb-0:5.3:1.0-joystick
E: TAGS=:uaccess:seat:
E: CURRENT_TAGS=:uaccess:seat:
```

**Comment by c02y** [comment]
It seems [def _get_device_description(device):](https://github.com/foresto/joystickwake/blob/72791f18b6a38ee3777d7b728fc8947552d161ec/joystickwake#LL384C37-L384C37) is only used for 
```
        self._log.info("%s is a joystick: %s",
            device.sys_name, self._get_device_description(device))

```
So 
> But if I change https://github.com/foresto/joystickwake/blob/72791f18b6a38ee3777d7b728fc8947552d161ec/joystickwake#LL384C37-L384C37
from
>```
>if bus:
>    bus = '(' + bus + ')'
>return ' '.join((vendor, model, bus)).strip()
>```
>to
>```
>if bus:
>    bus = '(' + bus + ')'
>    return ' '.join((vendor, model, bus)).strip()
>```
> The joystickwake script works without problem, at least for me, `waking the screen` part works.

Basically fixes it, or you want to handle this kind of virtual device for the log.

**Comment by foresto** [comment]
I just pushed a new release, which I think will handle your virtual device. Can you please test it and let me know how it goes?

**Comment by c02y** [comment]
It works, thanks.
