### ISSUE TITLE
Issue after system update

### ISSUE THREAD

**Issue by y-salnikov** [foresto/joystickwake#7]
Joystickwake no longer works after system update. I think it is because of python-3.10.
```/usr/bin/joystickwake:62: DeprecationWarning: There is no current event loop
  self._loop = loop or asyncio.get_event_loop()
/usr/bin/joystickwake:462: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
/usr/bin/joystickwake:193: DeprecationWarning: There is no current event loop
  self._loop = loop or asyncio.get_event_loop()
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fedcfd91750>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 124, in __del__
    if not self._closed:
AttributeError: '_UnixSubprocessTransport' object has no attribute '_closed'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'
joystickwake [17:40:24] Exception in callback ExecWaker._on_exec(<Task finishe...ment 'loop'")>)
handle: <Handle ExecWaker._on_exec(<Task finishe...ment 'loop'")>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/joystickwake", line 134, in _on_exec
    process = exectask.result()
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
TypeError: BaseSubprocessTransport.__init__() got multiple values for argument 'loop'```

**Comment by foresto** [comment]
Definitely caused by python 3.10.

The *no current event loop* deprecation warning is because the python maintainers are changing the behavior of asyncio.get_event_loop(), so it can no longer be used for preparing a loop before running it. I can work around that.

The *object has no attribute* and *multiple values for argument* exceptions seem to be python 3.10 making new assumptions about how event loops are prepared and used. I suppose I could spend a day unraveling asyncio's code to find the root of the problem, but it looks my deprecation workaround also fixes these errors, so I think I'll just commit the workaround and leave it at that.

**Comment by foresto** [comment]
@y-salnikov, what distribution are you using? Can you verify that my latest changes fix it on your system?

**Comment by y-salnikov** [comment]
Yes, it works now, thanks. I use arch, by the way. ) Didn't  expect such incompatibility from minor release of python.

**Comment by foresto** [comment]
I didn't expect it, either. (I hope this sort of thing doesn't become common now that Guido is gone.) Thanks for the report!
